spring:

  application:
    name: posts-server

  config:
    import: "optional:configserver:http://config-server:7777"

server:
  servlet:
    context-path: /posts-server
  port: 0
  error:
    include-exception: true
    include-stacktrace: always
    include-message: always

logging:
  level:
    com.arena: INFO

eureka:
  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://registry-server:8761/eureka/
