spring:

  application:
    name: images-server

  profiles:
    active: docker

  config:
    import: "optional:configserver:http://config-server:7777"

server:
  servlet:
    context-path: /images-server
  port: 0

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

images:
  path: ./images/

eureka:
  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://registry-server:8761/eureka/
