spring:

  application:
    name: events-server

  profiles:
    active: dev

  config:
    import: "optional:configserver:http://localhost:7777"

server:
  servlet:
    context-path: /events-server
  port: 0
  error:
    include-exception: true
    include-stacktrace: always
    include-message: always

logging:
  level:
    com.arena: INFO


eureka:
  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
