spring:
    application:
        name: notification-server
    profiles:
        active: dev
    config:
        import: "optional:configserver:http://localhost:7777"

server:
    servlet:
        context-path: /notification-server
    port: 0
    error:
        include-exception: true
        include-stacktrace: always
        include-message: always

logging:
    level:
        com.group3: INFO


eureka:
    instance:
        prefer-ip-address: true
        instance-id: "${spring.application.name}:${random.value}"
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
